/* determine the peak frequency from the time-frequency spectrum 
 * generated by sflh_timefreq
 * ============================================================
 * the program is developed by Luo Heng in Nanjing, CN, 23th, Dec, 2015
 */

#include <rsf.h>
#include "su_alloc.h"
#include "lh_wavelet.h"
#include "lh_readwrite.h"
#include "lh_mp.h"

int  main( int argc , char* argv[] )
{
    sf_init( argc , argv );

    sf_file FI1 , FO1;

    int dim, num_dim[SF_MAX_DIM], ncdp, icdp, iw, it, idim;

    float **gather_in , *gather_out;

    sf_axis at, aw;

    FI1 = sf_input( "in" );
    FO1 = sf_output( "out" );

    dim  = sf_filedims( FI1 , num_dim );
    ncdp = sf_leftsize( FI1 , 2 );

    at = sf_iaxa( FI1 , 1 );
    aw = sf_iaxa( FI1 , 2 );

    sf_oaxa( FO1 , at , 1 );
    for( idim=3 ; idim<=dim ; idim++ )
        sf_oaxa( FO1 , sf_iaxa( FI1 , idim ) , idim-1 );

    int   nt = sf_n( at );
    int   nw = sf_n( aw );
    float dw = sf_d( aw );
    float ow = sf_o( aw );

    float peak_value;
    int   peak_index;

    gather_in  = alloc2float( nt , nw );
    gather_out = alloc1float( nt );

    for( icdp=0 ; icdp<ncdp ; icdp++ )
    {
        zero2float( gather_in , nt , nw );
        zero1float( gather_out, nt );

        sf_seek( FI1 , sizeof(float)*(icdp*nt*nw) , SEEK_SET );
        sf_seek( FO1 , sizeof(float)*(icdp*nt)    , SEEK_SET );

        sf_floatread( &gather_in[0][0] , nt*nw , FI1 );

        for( it=0 ; it<nt ; it++ )
        {
            peak_value = 0.;
            peak_index = 0;
            for( iw=0 ; iw<nw ; iw++ )
            {
                if( peak_value < gather_in[iw][it] )
                {
                    peak_value = gather_in[iw][it];
                    peak_index = iw;
                }
            }
            gather_out[it] = ow + (float)peak_index*dw;
        }
        sf_floatwrite( &gather_out[0] , nt , FO1 );
    }

    exit( 0 );
}
