/* This file is automatically generated. DO NOT EDIT! */

#ifndef _tl_bayesian_h
#define _tl_bayesian_h


void tl_normalize(float *a	/*Arrary A*/,
		  float *b 	/*Array B*/,
		  int n		/*length of A*/);
/*< normalize an array using max value >*/


void tl_normalize2d(float **a   /*Array A*/,
		    float **b   /*Array B*/,
		    int n1 	/*Fast dimention*/,
		    int n2 	/*Slow dimention*/);
/*< normalize a 2D array using max value >*/

#endif
